apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: online-boutique
  description: online retail shop
spec:
  owner: default/retail-team
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: retail-team
spec:
  type: team
  children: []
  members: [muncus]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: online-boutique
  name: frontend
  annotations:
    backstage.io/kubernetes-label-selector: 'app=frontend'
spec:
  type: website
  lifecycle: production
  owner: default/retail-team
  system: default/online-boutique
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: online-boutique
  name: cartservice
  annotations:
    backstage.io/kubernetes-label-selector: 'app=cartservice'
spec:
  type: service
  lifecycle: production
  owner: default/retail-team
  system: default/online-boutique
